name: CI

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run tests
        run: |
          chmod +x test.sh
          ./test.sh

      - name: Build application
        run: |
          chmod +x build.sh
          ./build.sh
